CREATE TABLE item_pedido
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    quantidade INTEGER,
    observacao VARCHAR(255),
    pedido_id  BIGINT,
    plate_id   BIGINT,
    CONSTRAINT pk_itempedido PRIMARY KEY (id)
);

ALTER TABLE item_pedido
    ADD CONSTRAINT FK_ITEMPEDIDO_ON_PEDIDO FOREIGN KEY (pedido_id) REFERENCES pedido (id);

ALTER TABLE item_pedido
    ADD CONSTRAINT FK_ITEMPEDIDO_ON_PLATE FOREIGN KEY (plate_id) REFERENCES pratos (id);